# >>> Nexus AutoStart >>>
# Auto-generated by Enable-NexusAutoStart
$nexusRoot = 'C:\Users\RobinPieterse\OneDrive - Turrito Networks\Documents\GitHub\Nexus'
$modulePath = Join-Path $nexusRoot 'Nexus.psd1'
$settingsPath = Join-Path $nexusRoot 'Config/settings.local.json'

if (Test-Path $modulePath) {
    if (-not (Test-Path $settingsPath)) {
        $settingsPath = Join-Path $nexusRoot 'Config/settings.json'
    }

    $portsToCheck = @(8090)
    try {
        if (Test-Path $settingsPath) {
            $settings = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json
            if ($null -ne $settings.portRange -and $settings.portRange.Count -ge 2) {
                $startPort = [int]$settings.portRange[0]
                $endPort = [int]$settings.portRange[1]
                if ($endPort -ge $startPort) {
                    $portsToCheck = @($startPort..$endPort)
                }
            } elseif ($null -ne $settings.defaultPort) {
                $portsToCheck = @([int]$settings.defaultPort)
            }
        }
    } catch {
        $portsToCheck = @(8090)
    }

    $alreadyRunning = $false
    foreach ($port in $portsToCheck) {
        try {
            $null = Invoke-RestMethod -Uri "http://localhost:$port/api/health" -TimeoutSec 1
            $alreadyRunning = $true
            break
        } catch {
            # Keep probing remaining ports.
        }
    }

    if (-not $alreadyRunning) {
        $cmd = "Import-Module '$modulePath' -Force; Start-Nexus -NoBrowser"
        Start-Process pwsh -WindowStyle Hidden -ArgumentList '-NoLogo', '-NoProfile', '-Command', $cmd | Out-Null
    }
}
# <<< Nexus AutoStart <<<



