function Enable-NexusAutoStart {
    <#
    .SYNOPSIS
        Adds or updates a PowerShell profile block to auto-start Nexus.
    .DESCRIPTION
        Writes an idempotent profile snippet that starts Nexus in a hidden background
        PowerShell process when a new shell opens, only if Nexus is not already running.
    .PARAMETER NexusRoot
        Path to the Nexus repository root that contains Nexus.psd1.
        Defaults to this module's parent folder.
    .PARAMETER Scope
        Profile scope to update. AllHosts updates CurrentUserAllHosts;
        CurrentHost updates CurrentUserCurrentHost.
    .EXAMPLE
        Enable-NexusAutoStart
    .EXAMPLE
        Enable-NexusAutoStart -NexusRoot (Get-Location).Path -Scope CurrentHost
    #>
    [CmdletBinding()]
    param(
        [string]$NexusRoot = (Split-Path -Parent $PSScriptRoot),

        [ValidateSet('AllHosts', 'CurrentHost')]
        [string]$Scope = 'AllHosts'
    )

    $resolvedRoot = (Resolve-Path -Path $NexusRoot -ErrorAction Stop).Path
    $modulePath = Join-Path $resolvedRoot 'Nexus.psd1'
    if (-not (Test-Path -Path $modulePath -PathType Leaf)) {
        throw "Nexus module manifest not found at '$modulePath'."
    }

    $profilePath = if ($Scope -eq 'AllHosts') {
        $PROFILE.CurrentUserAllHosts
    } else {
        $PROFILE.CurrentUserCurrentHost
    }

    $profileDir = Split-Path -Parent $profilePath
    if (-not (Test-Path -Path $profileDir -PathType Container)) {
        New-Item -Path $profileDir -ItemType Directory -Force | Out-Null
    }
    if (-not (Test-Path -Path $profilePath -PathType Leaf)) {
        New-Item -Path $profilePath -ItemType File -Force | Out-Null
    }

    $startMarker = '# >>> Nexus AutoStart >>>'
    $endMarker = '# <<< Nexus AutoStart <<<'

    $escapedRoot = $resolvedRoot.Replace("'", "''")
    $snippetLines = @(
        $startMarker
        '# Auto-generated by Enable-NexusAutoStart'
        ("`$nexusRoot = '{0}'" -f $escapedRoot)
        "`$modulePath = Join-Path `$nexusRoot 'Nexus.psd1'"
        "`$settingsPath = Join-Path `$nexusRoot 'Config/settings.local.json'"
        ''
        'if (Test-Path $modulePath) {'
        '    if (-not (Test-Path $settingsPath)) {'
        '        $settingsPath = Join-Path $nexusRoot ''Config/settings.json'''
        '    }'
        ''
        '    $portsToCheck = @(8090)'
        '    try {'
        '        if (Test-Path $settingsPath) {'
        '            $settings = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json'
        '            if ($null -ne $settings.portRange -and $settings.portRange.Count -ge 2) {'
        '                $startPort = [int]$settings.portRange[0]'
        '                $endPort = [int]$settings.portRange[1]'
        '                if ($endPort -ge $startPort) {'
        '                    $portsToCheck = @($startPort..$endPort)'
        '                }'
        '            } elseif ($null -ne $settings.defaultPort) {'
        '                $portsToCheck = @([int]$settings.defaultPort)'
        '            }'
        '        }'
        '    } catch {'
        '        $portsToCheck = @(8090)'
        '    }'
        ''
        '    $alreadyRunning = $false'
        '    foreach ($port in $portsToCheck) {'
        '        try {'
        '            # 127.0.0.1, not localhost: the listener prefix only matches that host,'
        '            # so a localhost probe always fails and would start a duplicate Nexus.'
        '            $null = Invoke-RestMethod -Uri "http://127.0.0.1:$port/api/health" -TimeoutSec 1'
        '            $alreadyRunning = $true'
        '            break'
        '        } catch {'
        '            # Keep probing remaining ports.'
        '        }'
        '    }'
        ''
        '    if (-not $alreadyRunning) {'
        '        $cmd = "Import-Module ''$modulePath'' -Force; Start-Nexus -NoBrowser"'
        '        Start-Process pwsh -WindowStyle Hidden -ArgumentList ''-NoLogo'', ''-NoProfile'', ''-Command'', $cmd | Out-Null'
        '    }'
        '}'
        $endMarker
        ''
    )
    $snippet = $snippetLines -join "`r`n"

    $content = Get-Content -Path $profilePath -Raw
    $escapedStart = [regex]::Escape($startMarker)
    $escapedEnd = [regex]::Escape($endMarker)
    $pattern = "(?s)$escapedStart.*?$escapedEnd"

    if ($content -match $pattern) {
        $updated = [regex]::Replace($content, $pattern, $snippet)
    } else {
        if ($content.Length -gt 0 -and -not $content.EndsWith("`r`n")) {
            $content += "`r`n"
        }
        $updated = $content + $snippet
    }

    Set-Content -Path $profilePath -Value $updated -Encoding UTF8

    [pscustomobject]@{
        ProfilePath = $profilePath
        Scope       = $Scope
        NexusRoot   = $resolvedRoot
    }
}
